// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import type { AzureSupportedClouds } from "./static-helpers/cloudSettingHelpers.js";
import { AzureClouds } from "./static-helpers/cloudSettingHelpers.js";
import type {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { CommunityClient } from "./communityClient.js";
export { restorePoller, type RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  type Operation,
  type OperationDisplay,
  KnownOrigin,
  type Origin,
  KnownActionType,
  type ActionType,
  type ErrorResponse,
  type ErrorDetail,
  type ErrorAdditionalInfo,
  type CommunityTraining,
  type CommunityTrainingProperties,
  type IdentityConfigurationProperties,
  KnownProvisioningState,
  type ProvisioningState,
  type Sku,
  type SkuTier,
  type TrackedResource,
  type Resource,
  type SystemData,
  KnownCreatedByType,
  type CreatedByType,
  type CommunityTrainingUpdate,
  type CommunityTrainingUpdateProperties,
  KnownVersions,
  type ErrorDetail_1,
  type ErrorDetailAutoGenerated,
} from "./models/index.js";
export type { CommunityClientOptionalParams } from "./api/index.js";
export type {
  CommunityTrainingsListBySubscriptionOptionalParams,
  CommunityTrainingsListByResourceGroupOptionalParams,
  CommunityTrainingsDeleteOptionalParams,
  CommunityTrainingsUpdateOptionalParams,
  CommunityTrainingsCreateOptionalParams,
  CommunityTrainingsGetOptionalParams,
} from "./api/communityTrainings/index.js";
export type { OperationsListOptionalParams } from "./api/operations/index.js";
export type { CommunityTrainingsOperations, OperationsOperations } from "./classic/index.js";
export type { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
export { AzureClouds, type AzureSupportedClouds };
